// Auto-generated by scripts/measure-bezel.mjs
// Run: npm run measure-bezel -- src/assets/images/monitor-final.png
// Source: src/assets/images/monitor-final.png (1536×1024)
// Cutout: left=190px top=111px right=1345px bottom=811px
// Area ratio: 51.5%

import monitorPng from '../assets/images/monitor-final.png'
export { monitorPng }

export const BEZEL = {
  screen: {
    left:   12.370,   // vw  (190/1536)
    top:    10.840,    // vh  (111/1024)
    width:  75.260,  // vw  (1156/1536)
    height: 68.457, // vh  (701/1024)
  },
  /** Y position of screen center as % of 100vh — used for power-off transformOrigin */
  transformOriginY: 45.068,
  /** Pixels the wrapper extends beyond screen edges — bezel PNG always overlaps */
  bleedPx: 6,
  /** Inner padding: bleedPx + 2px buffer — content stays clear of bezel */
  paddingPx: 8,
} as const
