// Auto-generated by scripts/measure-bezel.mjs
// Run: npm run measure-bezel -- src/assets/images/monitor-final-v2.png
// Source: src/assets/images/monitor-final-v2.png (1536×1024)
// Cutout: left=115px top=80px right=1418px bottom=823px
// Area ratio: 61.7%

import monitorPng from '../assets/images/monitor-final-v2.png'
export { monitorPng }

export const BEZEL = {
  screen: {
    left:   7.487,   // vw  (115/1536)
    top:    7.813,    // vh  (80/1024)
    width:  84.896,  // vw  (1304/1536)
    height: 72.656, // vh  (744/1024)
  },
  /** Y position of screen center as % of 100vh — used for power-off transformOrigin */
  transformOriginY: 44.141,
  /** Pixels the wrapper extends beyond screen edges — bezel PNG always overlaps */
  bleedPx: 6,
  /** Inner padding: bleedPx + 2px buffer — content stays clear of bezel */
  paddingPx: 8,
} as const
