/**
 * measure-bezel.mjs
 *
 * Reads a monitor PNG, finds the transparent screen cutout via alpha channel,
 * computes viewport percentages, and writes src/config/bezel.ts.
 *
 * Usage:
 *   npm run measure-bezel                              # uses monitor-final.png (default)
 *   npm run measure-bezel -- src/assets/images/foo.png # uses a specific PNG
 *
 * Requires: pngjs (npm install -D pngjs)
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs'
import { resolve, relative, basename, dirname } from 'path'
import { fileURLToPath } from 'url'
import { PNG } from 'pngjs'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')

// ── Resolve PNG path ──────────────────────────────────────────────────────────

const DEFAULT_PNG = 'src/assets/images/monitor-final.png'
const pngArg = process.argv[2]
const pngRelPath = pngArg ?? DEFAULT_PNG
const pngAbsPath = resolve(ROOT, pngRelPath)

if (!existsSync(pngAbsPath)) {
  console.error(`✗ PNG not found: ${pngRelPath}`)
  console.error(`  Run: npm run measure-bezel -- <path-to-png>`)
  process.exit(1)
}

// ── Decode PNG ────────────────────────────────────────────────────────────────

const buffer = readFileSync(pngAbsPath)
const png = PNG.sync.read(buffer)
const { width, height, data } = png

console.log(`  PNG: ${basename(pngAbsPath)} (${width}×${height})`)

// ── Scan alpha channel for transparent screen cutout ─────────────────────────

let left = width
let top = height
let right = -1
let bottom = -1

for (let y = 0; y < height; y++) {
  for (let x = 0; x < width; x++) {
    const alpha = data[(y * width + x) * 4 + 3]
    if (alpha < 128) {
      if (x < left)   left   = x
      if (x > right)  right  = x
      if (y < top)    top    = y
      if (y > bottom) bottom = y
    }
  }
}

if (right === -1) {
  console.error('✗ No transparent pixels found. Is the screen cutout alpha=0?')
  process.exit(1)
}

// ── Validate: screen area must be ≥ 40% of total PNG area ────────────────────

const screenPixels = (right - left + 1) * (bottom - top + 1)
const totalPixels  = width * height
const screenRatio  = screenPixels / totalPixels

if (screenRatio < 0.40) {
  console.error(`✗ Detected screen area is only ${(screenRatio * 100).toFixed(1)}% of the PNG.`)
  console.error('  Expected ≥ 40%. This may be the wrong PNG or transparency was not properly set.')
  console.error(`  Bounds found: left=${left} top=${top} right=${right} bottom=${bottom}`)
  process.exit(1)
}

// ── Compute percentages ───────────────────────────────────────────────────────

const screenLeft   = (left   / width)  * 100
const screenTop    = (top    / height) * 100
const screenWidth  = ((right - left + 1) / width)  * 100
const screenHeight = ((bottom - top + 1) / height) * 100

// Power-off animation transformOrigin Y = screen center as % of 100vh
// (section is h-screen = 100vh; screen starts at screenTop vh)
const transformOriginY = screenTop + screenHeight / 2

// ── Constants (design decisions, not measured) ────────────────────────────────

const BLEED_PX   = 6   // px overlap on all sides — bezel always covers wrapper edges
const PADDING_PX = 8   // inner padding (bleedPx + 2px buffer)

// ── Print results ─────────────────────────────────────────────────────────────

console.log(`  Cutout: left=${left}px top=${top}px right=${right}px bottom=${bottom}px`)
console.log(`  Screen: ${screenLeft.toFixed(3)}vw, ${screenTop.toFixed(3)}vh,  ${screenWidth.toFixed(3)}vw × ${screenHeight.toFixed(3)}vh`)
console.log(`  Area ratio: ${(screenRatio * 100).toFixed(1)}% ✓`)
console.log(`  transformOriginY: ${transformOriginY.toFixed(3)}%`)

// ── Generate bezel.ts ─────────────────────────────────────────────────────────

const pngImportPath = relative(resolve(ROOT, 'src/config'), pngAbsPath)
  .replace(/\\/g, '/')  // normalise Windows paths

const output = `// Auto-generated by scripts/measure-bezel.mjs
// Run: npm run measure-bezel -- ${pngRelPath.replace(/\\/g, '/')}
// Source: ${pngRelPath.replace(/\\/g, '/')} (${width}×${height})
// Cutout: left=${left}px top=${top}px right=${right}px bottom=${bottom}px
// Area ratio: ${(screenRatio * 100).toFixed(1)}%

import monitorPng from '${pngImportPath}'
export { monitorPng }

export const BEZEL = {
  screen: {
    left:   ${screenLeft.toFixed(3)},   // vw  (${left}/${width})
    top:    ${screenTop.toFixed(3)},    // vh  (${top}/${height})
    width:  ${screenWidth.toFixed(3)},  // vw  (${right - left + 1}/${width})
    height: ${screenHeight.toFixed(3)}, // vh  (${bottom - top + 1}/${height})
  },
  /** Y position of screen center as % of 100vh — used for power-off transformOrigin */
  transformOriginY: ${transformOriginY.toFixed(3)},
  /** Pixels the wrapper extends beyond screen edges — bezel PNG always overlaps */
  bleedPx: ${BLEED_PX},
  /** Inner padding: bleedPx + 2px buffer — content stays clear of bezel */
  paddingPx: ${PADDING_PX},
} as const
`

const outPath = resolve(ROOT, 'src/config/bezel.ts')
mkdirSync(resolve(ROOT, 'src/config'), { recursive: true })
writeFileSync(outPath, output, 'utf8')
console.log(`✓ Written: src/config/bezel.ts`)
